undo docker compose

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -135,135 +135,135 @@ services:
       - ALLOW_PLAINTEXT_LISTENER=yes # FIXME: kafka gives warning for this
     volumes:
       - kafka_data:/bitnami/kafka
-  # postgres:
-  #   image: postgres:13
-  #   environment:
-  #     POSTGRES_USER: airflow
-  #     POSTGRES_PASSWORD: airflow
-  #     POSTGRES_DB: airflow
-  #   volumes:
-  #     - postgres_data:/var/lib/postgresql/data
-  # airflow-webserver:
-  #   <<: *airflow-common
-  #   command: webserver
-  #   ports:
-  #     - "8080:8080"
-  #   depends_on:
-  #     <<: *airflow-common-depends-on
-  #     airflow-init:
-  #       condition: service_completed_successfully
-  # airflow-scheduler:
-  #   <<: *airflow-common
-  #   command: scheduler
-  #   depends_on:
-  #     <<: *airflow-common-depends-on
-  #     airflow-init:
-  #       condition: service_completed_successfully
-  # airflow-worker:
-  #   <<: *airflow-common
-  #   command: celery worker
-  #   environment:
-  #     <<: *airflow-common-env
-  #     DUMB_INIT_SETSID: "0"
-  #   depends_on:
-  #     <<: *airflow-common-depends-on
-  #     airflow-init:
-  #       condition: service_completed_successfully
-  # airflow-triggerer:
-  #   <<: *airflow-common
-  #   command: triggerer
-  #   depends_on:
-  #     <<: *airflow-common-depends-on
-  #     airflow-init:
-  #       condition: service_completed_successfully
-  # airflow-init:
-  #   <<: *airflow-common
-  #   entrypoint: /bin/bash
-  #   command:
-  #     - -c
-  #     - |
-  #       function ver() {
-  #         printf "%04d%04d%04d%04d" $${1//./ }
-  #       }
-  #       airflow_version=$$(AIRFLOW__LOGGING__LOGGING_LEVEL=INFO && gosu airflow airflow version)
-  #       airflow_version_comparable=$$(ver $${airflow_version})
-  #       min_airflow_version=2.2.0
-  #       min_airflow_version_comparable=$$(ver $${min_airflow_version})
-  #       if (( airflow_version_comparable < min_airflow_version_comparable )); then
-  #         echo
-  #         echo -e "\033[1;31mERROR!!!: Too old Airflow version $${airflow_version}!\e[0m"
-  #         echo "The minimum Airflow version supported: $${min_airflow_version}. Only use this or higher!"
-  #         echo
-  #         exit 1
-  #       fi
-  #       if [[ -z "${AIRFLOW_UID}" ]]; then
-  #         echo
-  #         echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
-  #         echo "If you are on Linux, you SHOULD follow the instructions below to set "
-  #         echo "AIRFLOW_UID environment variable, otherwise files will be owned by root."
-  #         echo "For other operating systems you can get rid of the warning with manually created .env file:"
-  #         echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user"
-  #         echo
-  #       fi
-  #       one_meg=1048576
-  #       mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
-  #       cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
-  #       disk_available=$$(df / | tail -1 | awk '{print $$4}')
-  #       warning_resources="false"
-  #       if (( mem_available < 4000 )) ; then
-  #         echo
-  #         echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
-  #         echo "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
-  #         echo
-  #         warning_resources="true"
-  #       fi
-  #       if (( cpus_available < 2 )); then
-  #         echo
-  #         echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
-  #         echo "At least 2 CPUs recommended. You have $${cpus_available}"
-  #         echo
-  #         warning_resources="true"
-  #       fi
-  #       if (( disk_available < one_meg * 10 )); then
-  #         echo
-  #         echo -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
-  #         echo "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
-  #         echo
-  #         warning_resources="true"
-  #       fi
-  #       if [[ $${warning_resources} == "true" ]]; then
-  #         echo
-  #         echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
-  #         echo "Please follow the instructions to increase amount of resources available:"
-  #         echo "   https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#before-you-begin"
-  #         echo
-  #       fi
-  #       mkdir -p /sources/logs /sources/dags /sources/plugins
-  #       chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
-  #       exec /entrypoint airflow version
-  #   environment:
-  #     <<: *airflow-common-env
-  #     _AIRFLOW_DB_MIGRATE: "true"
-  #     _AIRFLOW_WWW_USER_CREATE: "true"
-  #     _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
-  #     _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
-  #   user: "0:0"
-  #   volumes:
-  #     - ./airflow:/sources
-  # airflow-cli:
-  #   <<: *airflow-common
-  #   profiles:
-  #     - debug
-  #   environment:
-  #     <<: *airflow-common-env
-  #     CONNECTION_CHECK_MAX_COUNT: "0"
-  #   command:
-  #     - bash
-  #     - -c
-  #     - airflow
+  postgres:
+    image: postgres:13
+    environment:
+      POSTGRES_USER: airflow
+      POSTGRES_PASSWORD: airflow
+      POSTGRES_DB: airflow
+    volumes:
+      - postgres_data:/var/lib/postgresql/data
+  airflow-webserver:
+    <<: *airflow-common
+    command: webserver
+    ports:
+      - "8080:8080"
+    depends_on:
+      <<: *airflow-common-depends-on
+      airflow-init:
+        condition: service_completed_successfully
+  airflow-scheduler:
+    <<: *airflow-common
+    command: scheduler
+    depends_on:
+      <<: *airflow-common-depends-on
+      airflow-init:
+        condition: service_completed_successfully
+  airflow-worker:
+    <<: *airflow-common
+    command: celery worker
+    environment:
+      <<: *airflow-common-env
+      DUMB_INIT_SETSID: "0"
+    depends_on:
+      <<: *airflow-common-depends-on
+      airflow-init:
+        condition: service_completed_successfully
+  airflow-triggerer:
+    <<: *airflow-common
+    command: triggerer
+    depends_on:
+      <<: *airflow-common-depends-on
+      airflow-init:
+        condition: service_completed_successfully
+  airflow-init:
+    <<: *airflow-common
+    entrypoint: /bin/bash
+    command:
+      - -c
+      - |
+        function ver() {
+          printf "%04d%04d%04d%04d" $${1//./ }
+        }
+        airflow_version=$$(AIRFLOW__LOGGING__LOGGING_LEVEL=INFO && gosu airflow airflow version)
+        airflow_version_comparable=$$(ver $${airflow_version})
+        min_airflow_version=2.2.0
+        min_airflow_version_comparable=$$(ver $${min_airflow_version})
+        if (( airflow_version_comparable < min_airflow_version_comparable )); then
+          echo
+          echo -e "\033[1;31mERROR!!!: Too old Airflow version $${airflow_version}!\e[0m"
+          echo "The minimum Airflow version supported: $${min_airflow_version}. Only use this or higher!"
+          echo
+          exit 1
+        fi
+        if [[ -z "${AIRFLOW_UID}" ]]; then
+          echo
+          echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
+          echo "If you are on Linux, you SHOULD follow the instructions below to set "
+          echo "AIRFLOW_UID environment variable, otherwise files will be owned by root."
+          echo "For other operating systems you can get rid of the warning with manually created .env file:"
+          echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user"
+          echo
+        fi
+        one_meg=1048576
+        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
+        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
+        disk_available=$$(df / | tail -1 | awk '{print $$4}')
+        warning_resources="false"
+        if (( mem_available < 4000 )) ; then
+          echo
+          echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
+          echo "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
+          echo
+          warning_resources="true"
+        fi
+        if (( cpus_available < 2 )); then
+          echo
+          echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
+          echo "At least 2 CPUs recommended. You have $${cpus_available}"
+          echo
+          warning_resources="true"
+        fi
+        if (( disk_available < one_meg * 10 )); then
+          echo
+          echo -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
+          echo "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
+          echo
+          warning_resources="true"
+        fi
+        if [[ $${warning_resources} == "true" ]]; then
+          echo
+          echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
+          echo "Please follow the instructions to increase amount of resources available:"
+          echo "   https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#before-you-begin"
+          echo
+        fi
+        mkdir -p /sources/logs /sources/dags /sources/plugins
+        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
+        exec /entrypoint airflow version
+    environment:
+      <<: *airflow-common-env
+      _AIRFLOW_DB_MIGRATE: "true"
+      _AIRFLOW_WWW_USER_CREATE: "true"
+      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
+      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
+    user: "0:0"
+    volumes:
+      - ./airflow:/sources
+  airflow-cli:
+    <<: *airflow-common
+    profiles:
+      - debug
+    environment:
+      <<: *airflow-common-env
+      CONNECTION_CHECK_MAX_COUNT: "0"
+    command:
+      - bash
+      - -c
+      - airflow
 
 volumes:
-  # postgres_data:
+  postgres_data:
   mongodata: {}
   redisdata: {}
   ch_data: {}
